import { escapeHTML, avatarMarkup } from '../../shared/dom.js';

export function profileMarkup({ id, graph, state }) {
  const account = state.account?.id===id ? state.account : null;
  const person=graph.objects.find((object)=>object.id===id && object.type==='person') || (account ? {id:account.id,type:'person',title:account.displayName,handle:account.email.split('@')[0],bio:'Libre member building a public knowledge identity.',avatar:account.displayName.slice(0,2).toUpperCase()} : null);
  if(!person) return `<section class="page"><div class="empty-state"><div><h2>Creator not found</h2></div></div></section>`;
  const pubs=graph.objects.filter((object)=>object.creatorId===id && object.type==='publication');
  const claims=graph.objects.filter((object)=>object.creatorId===id && object.type==='claim');
  const sources=graph.objects.filter((object)=>object.creatorId===id && ['source','document','dataset'].includes(object.type));
  const trails=graph.objects.filter((object)=>object.creatorId===id && object.type==='trail');
  const topics=[...new Set([...pubs,...claims,...sources].flatMap((object)=>object.topicIds||[]))].map((topicId)=>graph.objects.find((object)=>object.id===topicId)).filter(Boolean);
  const max=Math.max(...topics.map((topic)=>[...pubs,...claims,...sources].filter((object)=>(object.topicIds||[]).includes(topic.id)).length),1);
  return `<section class="page"><header class="profile-hero"><div><div style="display:flex;align-items:center;gap:18px;margin-bottom:24px">${avatarMarkup(person,'large')}<div><span style="color:var(--muted)">@${escapeHTML(person.handle||'creator')}</span></div></div><h1 class="profile-name">${escapeHTML(person.title)}</h1><p class="profile-bio">${escapeHTML(person.bio||'Libre creator')}</p><div class="signal-actions"><button class="primary-button" data-follow-entity="${person.id}">${state.following.includes(person.id)?'Following':'Follow'}</button><button class="quiet-button">Share knowledge map</button></div></div><aside><div class="divider-label">Knowledge identity</div><div class="knowledge-map">${topics.map((topic)=>{const count=[...pubs,...claims,...sources].filter((object)=>(object.topicIds||[]).includes(topic.id)).length;return `<div class="knowledge-bar"><span>${escapeHTML(topic.title)}</span><i style="width:${Math.max(12,(count/max)*100)}%"></i><strong>${count}</strong></div>`}).join('')}</div></aside></header><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--line);border-bottom:1px solid var(--line)"><div style="background:var(--bg);padding:24px"><strong style="font-size:2rem">${pubs.length}</strong><small style="display:block;color:var(--muted)">SPACES</small></div><div style="background:var(--bg);padding:24px"><strong style="font-size:2rem">${claims.length}</strong><small style="display:block;color:var(--muted)">CLAIMS</small></div><div style="background:var(--bg);padding:24px"><strong style="font-size:2rem">${sources.length}</strong><small style="display:block;color:var(--muted)">SOURCES</small></div><div style="background:var(--bg);padding:24px"><strong style="font-size:2rem">${trails.length}</strong><small style="display:block;color:var(--muted)">TRAILS</small></div></div><div class="page-heading"><div><h1 style="font-size:clamp(2.2rem,5vw,4rem)">Knowledge neighborhood</h1></div><p>Creator profiles are maps of what someone contributes, not a generic post grid.</p></div><div class="library-grid">${[...pubs,...claims,...sources,...trails].map((object)=>`<button class="library-item" data-open-object="${object.id}" style="background:transparent;text-align:left;border-left:0;border-right:0;border-bottom:0"><small style="color:var(--accent);text-transform:uppercase;letter-spacing:.08em">${escapeHTML(object.type.replaceAll('_',' '))}</small><h3>${escapeHTML(object.title)}</h3><p style="color:var(--muted)">${escapeHTML(object.summary||object.subtitle||object.evidenceState||'Connected object')}</p></button>`).join('')}</div></section>`;
}
