import { escapeHTML } from '../../shared/dom.js';
import { icon } from '../../shared/icons.js';

export function authModalMarkup(mode='login') {
  const signup=mode==='signup';
  return `<div class="modal-backdrop" data-auth-backdrop><section class="modal" role="dialog" aria-modal="true"><div style="display:flex;justify-content:space-between;align-items:start"><div><small style="color:var(--accent);text-transform:uppercase;letter-spacing:.1em">Libre identity</small><h2>${signup?'Create your knowledge identity':'Welcome back'}</h2></div><button class="icon-button" data-close-auth>${icon('close',17)}</button></div><p>${signup?'Publishing, following, persistent libraries, and forks require an account. Reading and anonymous discussion do not.':'Sign in to publish, fork, follow, and keep a persistent library.'}</p><form data-auth-form data-mode="${signup?'signup':'login'}">${signup?'<div class="field"><label>Display name</label><input name="displayName" required placeholder="Researcher name"></div>':''}<div class="field"><label>Email</label><input name="email" type="email" required placeholder="you@example.com"></div><div class="field"><label>Password</label><input name="password" type="password" required minlength="6" placeholder="6+ characters"></div><div class="modal-actions"><button type="button" class="quiet-button" data-switch-auth="${signup?'login':'signup'}">${signup?'Already have an account':'Create account'}</button><button class="primary-button" type="submit">${signup?'Create account':'Sign in'}</button></div></form><small style="display:block;color:var(--muted);margin-top:18px">Local V1 stores credentials only in this browser for development. Supabase Auth replaces this before public hosting.</small></section></div>`;
}

export function authPageMarkup(mode='login') {
  const signup=mode==='signup';
  return `<section class="page" style="max-width:1100px"><div style="display:grid;grid-template-columns:minmax(0,1fr) minmax(360px,.7fr);gap:80px;align-items:start;padding-top:60px"><div><small style="color:var(--accent);text-transform:uppercase;letter-spacing:.12em;font-weight:800">Libre identity</small><h1 style="font:500 clamp(3.5rem,8vw,7.5rem)/.88 var(--reading-font);letter-spacing:-.06em;margin:18px 0 26px">${signup?'Build a public knowledge identity.':'Continue where your curiosity left off.'}</h1><p style="max-width:640px;color:var(--text-2);font-size:1.15rem;line-height:1.7">Reading, searching, and anonymous discussion never require an account. An identity is only required when provenance needs an owner: publishing, forking, following, and persistent libraries.</p><div style="margin-top:38px;display:grid;gap:14px;max-width:580px"><div class="object-tool"><strong>Publish Knowledge Spaces</strong><small>Claims, sources, relationships, and Reader Paths keep their lineage.</small></div><div class="object-tool"><strong>Own your algorithm</strong><small>Saved knowledge and explicit controls shape discovery without hiding why.</small></div><div class="object-tool"><strong>Fork without erasing provenance</strong><small>Build another interpretation while preserving the original objects.</small></div></div></div><div class="modal" style="position:sticky;top:110px">${signup?'<h2>Create account</h2><p>Local development identity for this V1.</p>':'<h2>Log in</h2><p>Return to your Library, Trails, and Studio.</p>'}<form data-auth-form data-mode="${signup?'signup':'login'}">${signup?'<div class="field"><label>Display name</label><input name="displayName" required></div>':''}<div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Password</label><input name="password" type="password" minlength="6" required></div><button class="primary-button" type="submit" style="width:100%;margin-top:8px">${signup?'Create Libre identity':'Log in'}</button></form><button class="signal-action" style="margin-top:14px" data-route="/login/${signup?'login':'signup'}">${signup?'Already have an account? Log in':'New to Libre? Create account'}</button><small style="display:block;color:var(--muted);line-height:1.5;margin-top:22px">Local-only credentials are intentionally temporary. Production hosting replaces this adapter with Supabase Auth.</small></div></div></section>`;
}
